### ISSUE TITLE
Unable to connect users-phys.au.dk

### ISSUE THREAD

**Issue by 2BECKHAM2** [Robotto/ArduinoNodeMCU#1]
Thanks for the excellent application Robotto.

I'm unable to connect to users-phys.au.dk, observed the below output in serial monitor. 

.......
WiFi connected
IP address: 
192.168.31.233
connecting to users-phys.au.dk
Requesting URL: /vejrdata/vejret/WD/Stenomuseet.htm

closing connection
connecting to users-phys.au.dk
Requesting URL: /vejrdata/vejret/WD/Stenomuseet.htm

closing connection
The web page is displayed when accessed through the browser.

Request you to check the same. - Thanks in advance.

**Comment by Robotto** [comment]
yeah, sorry... this code only works if there's really low latency between your local network and phys.au.dk, which happened to be the case when i wrote it, while working at au.dk ... :)

I added a little waiting (and timeout) code to account for latency in this commit: https://github.com/Robotto/ArduinoNodeMCU/commit/1633c0d1d7ad1d65af2756ae27907b430ab70a9a

**Comment by Robotto** [comment]
Let me know if it works for you.
Autoclosing in one week.

**Comment by 2BECKHAM2** [comment]
Thanks for the quick response. Will check the updated code and revert. - Thanks.

**Comment by 2BECKHAM2** [comment]
Its working fine now. - Many thanks.

`
connecting to users-phys.au.dk
Requesting URL: /vejrdata/vejret/WD/Stenomuseet.htm
.
.
String: 2.2&d
float: 2.20
closing connection
`

Let me know how you capture the http response and calculate the line number.

`if(linecounter==31)`

**Comment by Robotto** [comment]
It's not really calculated.. Just sort of deduced.. Paste the source of the HTML into an editor with line numbers and you'll see.

**Comment by 2BECKHAM2** [comment]
OK. Thanks a lot Robotto.
